### ISSUE TITLE
Podman implementation 

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/docker-extension#22]
Do I understand correctly that this can only work with docker desktop "extensions" ? If so, is there any way to achieve similar functionality using other means on products such as podman ?

**Comment by rosszurowski** [comment]
This extension is just an easy one-click setup for sharing exposed ports from Docker containers over your Tailscale network with a nice UI. It doesn't do anything fancy. You should be able to achieve a similar effect simply by running Tailscale on the host machine.

Is there something in particular you're trying to do with Tailscale + Podman?

**Comment by JayDoubleu** [comment]
I see I might have misunderstood what this does. I was thinking about exposing containers/pods to tailscale network as separate IPs/clients

**Comment by DentonGentry** [comment]
https://hub.docker.com/r/tailscale/tailscale might be useful as a way to get the binaries into your system.

There are examples of Dockerfiles using userspace-networking, for environments where the docker container does not have a /dev/net/tun interface or does not have CAP_NET_ADMIN:
https://tailscale.com/kb/1113/aws-lambda/
https://tailscale.com/kb/1108/cloudrun/

Google search turns up example Dockerfiles for environments which do have /dev/net/tun available.

**Comment by JayDoubleu** [comment]
I see thanks for the info. This is very useful
