### ISSUE TITLE
Tailscale Desktop not assigning unique static IPs per device

### ISSUE THREAD

**Issue by jeffkni** [tailscale/docker-extension#40]
## Setup
- Docker Desktop with Tailscale extension v0.0.13
- Start containers with docker-compose - no networking specified; each container has a name in docker-compose
- Each container shows a unique name in docker desktop as expected ✅
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/104843262/186296522-c9c98ca9-c690-4d01-a0af-8643115f9ccf.png">

# Expected
- Tailscale also gives each container a unique ip -> magic dns name

## Actual
- Tailscale gives them all the same 100. IP address:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/104843262/186296688-2add23d1-05d9-4fd7-bfe0-800f0796e3c1.png">

- Enabling MagicDNS shows they're all assigned to the same docker-desktop dns name (host networking is not enabled):
<img width="813" alt="image" src="https://user-images.githubusercontent.com/104843262/186296825-d0ba6fe5-2c58-4439-beb7-8561a8d9537b.png">

**Comment by DentonGentry** [comment]
That is how the Docker Desktop extension works: there is one tailscaled, running in a Linux instance inside Docker Desktop. It forwards individual ports to each container.

It is not running a proxy tailscaled for each container. Even in the demo video linked to, all of the containers are on the same IP address with the same URL but different port numbers.

**Comment by jeffkni** [comment]
Thanks for the clarification @DentonGentry

**Comment by DentonGentry** [comment]
I think this is resolved.
