### ISSUE TITLE
Updating Tailscale docker extension from Docker Hub

### ISSUE THREAD

**Issue by brucejackson** [tailscale/docker-extension#48]
I notice that the Tailscale docker extension code has been updated to version 1.32.2.  However, in my Tailscale admin console the node running the docker extension shows that it only uses Tailscale 1.30.2.  I installed the extension via Docker Hub and the last version of the extension available is 0.0.14.  

Is there something I need to do to update my docker extension to 1.32.2?

Thanks,

**Comment by rosszurowski** [comment]
Sorry, this is an issue on our end. This repository was updated, but we didn't publish the latest version to the Docker marketplace. I've filed https://github.com/tailscale/docker-extension/issues/51 to track us fixing this with tooling, but in the meantime, I just published https://github.com/tailscale/docker-extension/releases/tag/0.0.15 to the Docker marketplace, so it should show up in Docker over the next 24 hours or so.
