### ISSUE TITLE
How to upgrade tailscale?

### ISSUE THREAD

**Issue by huyz** [tailscale/docker-extension#59]
Installing this extension seems to have installed Tailscale in Docker Desktop somehow.

But the version is outdated.  How can one upgrade Tailscale inside Docker for Windows?

**Comment by ssghost** [comment]
I have the same problem, waiting for an answer.

**Comment by TijsVK** [comment]
You can follow the build instructions, but update `ARG TSVERSION=1.48.1` to `ARG TSVERSION=1.56.1` (change this to be the most recent version) in the Dockerfile. 

The makefile is a little bugged, so I had to run `tailscale/docker-extension-dev:latest` to install it manually after building. 

The UI bugged out too for me when doing this, to connect manually you can simply go into the extension container cli (enable 'show extension containers' in settings) and run `/app/tailscale up`. (while you're there you might as well enable auto update[I haven't tested this] with `/app/tailscale set --auto-update`)

**Comment by ssghost** [comment]
I followed these steps but the last command `/app/tailscale set --auto-update` returned an error message says there is no "--auto-update" flag under "set" subcommand. I printed out all subcommands of "/app/tailscale" and found no subcommands is related with "update" or "upgrade". Here is the complete subcommands list:

`SUBCOMMANDS
  up         Connect to Tailscale, logging in if needed
  down       Disconnect from Tailscale
  set        Change specified preferences
  login      Log in to a Tailscale account
  logout     Disconnect from Tailscale and expire current node key
  switch     Switches to a different Tailscale account
  configure  [ALPHA] Configure the host to enable more Tailscale features
  netcheck   Print an analysis of local network conditions
  ip         Show Tailscale IP addresses
  status     Show state of tailscaled and its connections
  ping       Ping a host at the Tailscale layer, see how it routed
  nc         Connect to a port on a host, connected to stdin/stdout
  ssh        SSH to a Tailscale machine
  funnel     Turn on/off Funnel service
  serve      Serve content and local servers
  version    Print Tailscale version
  web        Run a web server for controlling Tailscale
  file       Send or receive files
  bugreport  Print a shareable identifier to help diagnose issues
  cert       Get TLS certs
  lock       Manage tailnet lock
  licenses   Get open source license information
  exit-node  `



> You can follow the build instructions, but update `ARG TSVERSION=1.48.1` to `ARG TSVERSION=1.56.1` (change this to be the most recent version) in the Dockerfile.
> 
> The makefile is a little bugged, so I had to run `tailscale/docker-extension-dev:latest` to install it manually after building.
> 
> The UI bugged out too for me when doing this, to connect manually you can simply go into the extension container cli (enable 'Settings>Extensions>show Docker Extension system containers' in settings) and run `/app/tailscale up`. (while you're there you might as well enable auto update[I haven't tested this] with `/app/tailscale set --auto-update`)

**Comment by TijsVK** [comment]
@ssghost According to this line 
> This will update Tailscale from 1.48.1 to 1.56.1. Continue? [y/n] y

It seems you did not properly build it using the changed dockerfile as 1.48.1 is the default (and auto-update is only available as a flag from version 1.52). As for the update command not working, I haven't tested the self-update functionality so I can't help with that.

**Comment by wimmme** [comment]
![image](https://github.com/tailscale/docker-extension/assets/5365731/8ac0b486-cfc9-4e91-9290-02fbec26b177)
Works for me ...

**Comment by huyz** [comment]
It's still an issue to me:

```shell
# /app/tailscale set --auto-update
# /app/tailscale update
no latest version found for "stable" track
# /app/tailscale version
1.58.2
  tailscale commit: 6a2a8457f0d62c775bfee3e350d2b34d85eda0f5
  other commit: 8c7d4563e46a1856053912ac067fc5036c2d2b3e
  go version: go1.21.5
```

**Comment by huyz** [comment]
> It's still an issue to me:

Oh it worked for me finally.
