### ISSUE TITLE
Keep docker-extension version synchronized with the stand-alone and app store versions

### ISSUE THREAD

**Issue by QuantumLibet** [tailscale/docker-extension#60]
THIS IS NOT AN ISSUE - just a feature request.
Please delete, if this is not the correct way to bring it up.

The version of the Docker extension always seems to lag behind the current version of the standalone program and the apps published in the app stores (or for qpkg, as far as I can tell). 

This is not a problem in itself, but could become one if security-related fixes are included in the updated version. In addition, the tailscale console always indicates that an update is available - which is not correct.

It would be great if it could be realized to update the Docker extension along with everything else.

Thank you. :)

**Comment by TijsVK** [comment]
Well, there is an update available, simply updating `ARG TSVERSION=1.48.1` to `ARG TSVERSION=1.56.1` in the Dockerfile creates a docker image with the latest version (at this time). 

Auto update was introduced in beta in 1.52, maybe when it comes out of beta and is on by default this will no longer be an issue. As an alternative solution, there really should be a download path like `https://pkgs.tailscale.com/stable/tailscale_latest_${TARGETARCH}.tgz` with the docker extension automatically updating when this is updated.

**Comment by QuantumLibet** [comment]
Thank you very much.

That would be a nice workaround. But, to be honest, I do not know where to find the extension's Dockerfile. Docker is not really transparent about where it stores the files of "Extensions" downloaded from its "Extensions Marketplace". `docker-extension extension ls` doesn't offer much info. I'd really appreciate a hint on where to look for the Dockerfile.

The latest version of the Tailscale extension on the marketplace (as of today) is v1.0.1. It would make much more sense (for me, as a simple user) if this would at least have the version of the included Tailscale binary, which is 1.48.1. 
And if that was kept in sync with the rest of the Tailscale releases, that would be perfect. Which, if I understand you correctly, might become a thing once the autoupdater comes out of beta. That sounds promising!

Thanks again! And have a nice day.

**Comment by TijsVK** [comment]
@QuantumLibet This is the repo from which the docker extension is build, in fact they provide a guide on how to make the extension in the README. As such the dockerfile can be found in the top folder. 

To build it with the most recent version: clone the repo, change the line in the Dockerfile[note that the version I mentioned in my reply is no longer the most recent version], follow instructions in the README to build and install it.

**Comment by QuantumLibet** [comment]
Thanks again.

I assumed I'd be able to change the config of the installed extension to somehow force it to pull a more updated version of tailscale.
